### ISSUE TITLE
Getting error "cannot access TJPlacementListener" when adding `tapjoy_offerwall^14.2.1`

### ISSUE THREAD

**Issue by crazyguysdev** [Tapjoy/flutter-sdk#1]
In my flutter project, I was adding `tapjoy_offerwall`, and there is error while building project.
As a workaround, The build failure can be resolved by adding dependency `implementation 'com.tapjoy:tapjoy-android-sdk:14.2.1'` on my project `app/build.gradle`, but it doesn't works properly on runtime. 

Here is error I got:
```
~~/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java:129: error: cannot access TJPlacementListener
      flutterEngine.getPlugins().add(new com.tapjoy.flutter.TapjoyOfferwallPlugin());
                                ^
  class file for com.tapjoy.TJPlacementListener not found
1 error

FAILURE: Build failed with an exception.
```

And here is my pubspec.yaml

```
environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.11.0
  # Add the dependency for the FlutterFire plugin for Google Analytics
  firebase_analytics: ^11.4.2
  firebase_auth: ^5.4.2
  cloud_functions: ^5.3.2
  cloud_firestore: ^5.6.3
  firebase_remote_config: ^5.4.0
  firebase_crashlytics: ^4.3.2
  firebase_messaging: ^15.2.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4
  provider: ^6.1.2
  flutter_svg: ^2.0.10+1

  # Easy Localization
  easy_localization: ^3.0.7+1
  uuid: ^4.4.0
  dart_json_mapper: ^2.2.14
  flutter_keyboard_visibility: ^6.0.0
  async: ^2.12.0
  google_sign_in: ^6.0.2
  flutter_facebook_auth: ^7.1.1
  crypto: ^3.0.1
  tapjoy_offerwall: ^14.2.1
  sign_in_with_apple: ^6.1.0
  lottie: ^3.1.0
  package_info_plus: ^8.2.0
  flutter_local_notifications: ^18.0.1
  fluttertoast: ^8.2.11
  device_info_plus: ^11.2.1
  flutter_launcher_icons: ^0.14.3
  google_mobile_ads: ^5.3.1
  synchronized: ^3.1.0
  scrollview_observer: ^1.25.1

dependency_overrides:
  meta: ^1.16.0
  async: ^2.12.0

dev_dependencies:
  build_runner:
```

And here is my flutter doctor result
```
[✓] Flutter (Channel stable, 3.27.4, on macOS 14.4.1 23E224 darwin-arm64, locale ko-KR)
    • Flutter version 3.27.4 on channel stable at /Users/user/Library/Flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d8a9f9a52e (6일 전), 2025-01-31 16:07:18 -0500
    • Engine revision 82bd5b7209
    • Dart version 3.6.2
    • DevTools version 2.40.3

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /Users/user/Library/Android/sdk/
    • Platform android-35, build-tools 35.0.0
    • ANDROID_HOME = /Users/user/Library/Android/sdk/
    • Java binary at: /Users/user/Library/Java/JavaVirtualMachines/azul-18.0.2.1/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment Zulu18.32+13-CA (build 18.0.2.1+1)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.4+-12422083-b607.1)

[✓] Android Studio (version 2023.3)
    • Android Studio at /Applications/Android Studio2.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[✓] IntelliJ IDEA Community Edition (version 2023.3.7)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.96.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (7 available)
    • Pixel 7 Pro (mobile)            • 2A201FDH300C7R        • android-arm64  • Android 15 (API 35)
    • SM S916N (mobile)               • R3CW10VZVNJ           • android-arm64  • Android 14 (API 34)
    • sdk gphone64 arm64 (mobile)     • emulator-5554         • android-arm64  • Android 14 (API 34) (emulator)
    • sdk gphone64 arm64 (mobile)     • emulator-5556         • android-arm64  • Android 15 (API 35) (emulator)
    • macOS (desktop)                 • macos                 • darwin-arm64   • macOS 14.4.1 23E224 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 14.4.1 23E224 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript • Google Chrome 129.0.6668.90

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```
